version: '3.1'

services:
  database:
    container_name: ecommerce_api_database
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=ecommerce_api
